const mongoose=require('mongoose');
const OrderSchema=new mongoose.Schema({
  shiping_info:{
    address:{
      type:String,
      required:true
    },
    city:{
      type:String,
      required:true,
    },
    state:{
      type:String,
      required:true,
    },
    phoneNumber:{
      type:Number,
      required:true
    }
  },
  OrderInfo:[{
    name:{
      type:String,
      required:true,
    },
    price:{
      type:Number,
      required:true,
    },
    quantity:{
      type:Number,
      required:true
    },
    Product_id:{
      type:mongoose.Schema.ObjectId,
      ref:"ProductModel"
    },
    image:{
      type:String,
      required:true,
    }
  }],
  user:{
    type:mongoose.Schema.ObjectId,
    ref:"UserModel"
  },
  OrderStatus:{
    type:String,
    default:"shipping"
  },
  Payment_status:{
    type:String,
    default:"pending"
  },
  paidInfo:{
    type:String,
  },
  paidAt:{
    type:Date,
    default: Date.now
  },
  other_price:{
    type:Number,
    default:0,
  },
  totalPrice:{
    type:Number,
    default:0,
  },
  deleviredAt:{
   type: Date,
  default: () => Date.now() + 7 * 24 * 60 * 60 * 1000
  }

},{timestamps:true});
module.exports=mongoose.model("OrderModel",OrderSchema);