const mongoose=require('mongoose');
const OrderSchema=new mongoose.Schema({
  shiping_info:{
    address:{
      type:String,
      required:true
    },
    city:{
      type:String,
      required:true,
    },
    state:{
      type:String,
      required:true,
    },
    pinCode:{
      type:Number,
      required:true,
    },
  },
  OrderInfo:[{
    name:{
      type:String,
      required:true,
    },
    price:{
      type:Number,
      required:true,
    },
    quantity:{
      type:Number,
      required:true
    },
    Product_id:{
      type:mongoose.Schema.ObjectId,
      ref:"ProductModel"
    },
    image:{
      type:String,
      required:true,
    }
  }],
  user:{
    type:mongoose.Schema.ObjectId,
    ref:"UserModel"
  },
  OrderStatus:{
    type:String,
    required:true,
    default:"processing"
  },
  paymentInfo:{
    id:{
      type:String,
    }
  },
  StatusInfo:{
    type:String,
    default:"pending"
  },
  paidInfo:{
    type:String,
  },
  paidAt:{
    type:Date,
  },
  itemPrice:{
    type:Number,
    default:0,
  },
  shippingPrice:{
    type:Number,
    default:0,
  },
  totalPrice:{
    type:Number,
    default:0,
  },
  deleviredAt:{
    type:Date,
  }

},{timestamps:true});
module.exports=mongoose.model("OrderModel",OrderSchema);